version: '3'
services:
  postgresdb:
    image: postgres
    container_name: postgres-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=docker # required variable, postgres username is by default 'postgres'
    volumes:
      - pgadmin:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 80:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    depends_on:
      - postgresdb

  aqi:
    build: .  # build this container's image using the Dockerfile
    volumes:
      - ./:/app/data # path of your host filesystem to container's filesystem
    depends_on:
      - postgresdb


volumes:
  pgadmin: